export const sliderItems = [
  {
    id: 1,
    img: "./pc.png",
    title: "LAPTOPS AND PC",
    desc: "IF YOU ARE LOOKING FOR BRAND NEW, LAPTOP AND PC, YOU ARE IN THE RIGHT PLACE!!",
    bg: "f5fafd",
    amount: 1,
  },
  {
    id: 2,
    img: "./pc2.png",
    title: "QUALITY PRODUCT WITH AFFORDABLE PRICE",
    desc: "DON'T COMPROMISE ON SPECIFICATIONS.",
    bg: "fcf1ed",
    amount: 1,
  },
  {
    id: 3,
    img: "./pc3.png",
    title: "LATEST SPECS",
    desc: "ARIVAL OF LATEST GEN LAPTOPS AND PRE-BUILT PC'S",
    bg: "fbf0f4",
    amount: 1,
  },
];

export const categories = [
  {
    id: 1,
    img: "./productImage/Lenovo.jpg",
    title: "LAPTOPS!",
    amount: 1,
  },
  {
    id: 2,
    img: "./productImage/prebuilt.jpg",
    title: "PRE-BUILT PC",
    amount: 1,
  },
  {
    id: 3,
    img: "./productImage/customn.jpg",
    title: "CUSTOMN PC",
    amount: 1,
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "./productImage/prod1.png",
    title: "ASUS GAMING",
    amount: 1,
    price: 69999,
    type: "laptop",
    desc: "This laptop comes with an internal memory of 3 GB. Existing users of this laptop have provided reviews claiming that it is easily portable and has a battery life of two hours which is less than what other laptops offer and are available in the market. The best feature of this laptop is that it has genuine Windows 7 which is suitable for a RAM of 2GB and hard drive of 320 GB. There are three USB ports for the usage of external devices (PC World, 2011).",
  },
  {
    id: 12,
    img: "./productImage/prod12.png",
    title: "HP GAMING",
    amount: 1,
    price: 189799,
    type: "pc",
    desc: "OMEN Matrix G G731GT-AU041T Gaming Laptop (10th Gen Core I7/ 8GB/ 512GB SSD/ Win10/ 8GB Graph)",
  },
  {
    id: 2,
    img: "./productImage/prod2.png",
    title: "OMEN GAMING",
    amount: 1,
    price: 411699,
    type: "laptop",
    desc: "The price of this laptop is £329.99 and has processing power of AMD E-450 processor. It is a dual-core processor which is suitable for multi-tasking and speedy computing experience. The battery life of this laptop is up to 8.5 hours which is quite suitable for longer work durations without the need of charging it. It has a hard drive of 320 GB.",
  },
  {
    id: 3,
    img: "./productImage/prod3.png",
    title: "LEGION GAMING",
    amount: 1,
    price: 199899,
    type: "laptop",
    desc: "The price of this laptop is £329.99 and it has a processor of Intel Pentium B950 with an internal memory of 4 GB which can be further extended by installing additional RAM. The hard dive available for the user computing experiences is 500GB. ",
  },
  {
    id: 9,
    img: "./productImage/prod9.png",
    title: "LENOVO GAMING",
    amount: 1,
    price: 299999,

    desc: "HP Strix G G731GT Gaming PC (12th Gen Core I7/ 8GB/ 512GB SSD/ Win11/ 8GB Graph)",
    type: "pc",
  },
  {
    id: 4,
    img: "./productImage/prod4.png",
    title: "HP GAMING",
    amount: 1,
    price: 311699,
    desc: "Asus ZenBook Flip 13 UX362FA Laptop (8th Gen Core I7/ 8GB/ 512GB SSD/ Win10)",
    type: "laptop",
  },
  {
    id: 8,
    img: "./productImage/prod8.png",
    title: "ACER GAMING",
    amount: 1,
    price: 331099,
    desc: "Asus ROG Strix Scar III G531GU-ES016T Gaming Laptop (9th Gen Core I7/ 16GB/ 1TB SSD/ Win10/ 6GB Graph)",
    type: "laptop",
  },
  {
    id: 6,
    img: "./productImage/prod6.png",
    title: "NITRO GAMING",
    amount: 1,
    price: 421699,
    desc: "Asus ZenBook Flip 14 UM462DA-AI501TS Laptop (AMD Quad Core R5/ 8GB/ 512GB SSD/ Win10)",
    type: "laptop",
  },
  {
    id: 7,
    img: "./productImage/prod7.png",
    title: "ARUS GAMING",
    amount: 1,
    price: 111299,
    desc: "HP EliteBook X360 (4SU65UT) Laptop (8th Gen Core I5/ 8GB/ 1TB 256GB SSD/ 8GB EMMC/ Win10/ 2GB Graph)",
    type: "laptop",
  },
  {
    id: 5,
    img: "./productImage/prod5.png",
    title: "NEXTGEN GAMING",
    amount: 1,
    price: 211699,
    desc: "Asus ROG Strix G G731GT-AU041T Gaming Laptop (9th Gen Core I5/ 8GB/ 512GB SSD/ Win10/ 4GB Graph)",
    type: "laptop",
  },

  {
    id: 10,
    img: "./productImage/prod10.png",
    title: "REAVER GAMING",
    amount: 1,
    price: 221699,
    desc: "REAVER H931GT-AU040T Gaming PC (12th Gen Core I9/ 8GB/ 512GB SSD/ Win11)",
    type: "pc",
  },
  {
    id: 11,
    img: "./productImage/prod11.png",
    title: "ACER GAMING",
    amount: 1,
    price: 111699,
    desc: "ACER Strix P Q731GT-UU041T Gaming PC (12th Gen Core I7/ 8GB/ 512GB SSD/ Win11/ 16GB Graph)",
    type: "pc",
  },
];
